services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./config/addons:/config/custom_components
      - ./config/media:/media
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Africa/Cairo
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  # Optional: for Zigbee/Z-Wave
    ports:
      - "8123:8123"
      - "1900:1900/udp"  # For device discovery
      - "5353:5353/udp"  # mDNS
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  voice_streaming:
    container_name: voice-streaming
    build: 
      context: ./webrtc_backend
    ports:
      - "8080:8080"
    environment:
      - TZ=Africa/Cairo
    restart: unless-stopped
    volumes:
      - ./webrtc_backend:/app

  # Optional: Nginx proxy for HTTPS (required for WebRTC)
  nginx:
    container_name: ha-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    depends_on:
      - homeassistant
      - voice_streaming

networks:
  default:
    driver: bridge