name: Voice Streaming WebRTC
version: "1.0.0"
slug: voice_streaming_webrtc
description: Real-time voice streaming using WebRTC with minimal latency
url: https://github.com/your-repo/voice-streaming-addon
webui: http://[HOST]:[PORT:8080]
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ports:
  8080/tcp: 8080
  3478/udp: 3478  # STUN
  5349/tcp: 5349  # TURNS
  49152:65535/udp: null  # RTP port range
ports_description:
  8080/tcp: Web interface
  3478/udp: STUN server
  5349/tcp: TURNS server
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  stun_servers:
    - "stun:stun.l.google.com:19302"
    - "stun:stun1.l.google.com:19302"
  ice_servers: []
  audio_settings:
    sample_rate: 16000
    channels: 1
    bit_depth: 16
  processing:
    noise_suppression: true
    echo_cancellation: true
    auto_gain_control: true
schema:
  ssl: bool
  certfile: str
  keyfile: str
  stun_servers: [str]
  ice_servers: [str]
  audio_settings:
    sample_rate: int
    channels: int
    bit_depth: int
  processing:
    noise_suppression: bool
    echo_cancellation: bool
    auto_gain_control: bool
image: ghcr.io/your-username/voice-streaming-{arch}